Matrices de rotacion

In [13]:
from sympy import cos, sin, symbols
import numpy as np

In [14]:
thetax, thetay, thetaz = symbols('thetax thetay thetaz')


In [15]:
cx, sx = cos(thetax), sin(thetax)
cy, sy = cos(thetay), sin(thetay)
cz, sz = cos(thetaz), sin(thetaz)

Matriz Rx

In [16]:
Rx = np.array([[1,0,0],
               [0, cx, -sx],
               [0, sx, cx]])

print(Rx)

[[1 0 0]
 [0 cos(thetax) -sin(thetax)]
 [0 sin(thetax) cos(thetax)]]


Matriz Ry

In [17]:
Ry = np.array([[cy, 0, sy],
               [0, 1, 0],
               [-sy, 0, cy]])
print(Ry)

[[cos(thetay) 0 sin(thetay)]
 [0 1 0]
 [-sin(thetay) 0 cos(thetay)]]


Matriz Rz

In [18]:
Rz = np.array([[cz, -sz,0],
               [sz, cz, 0],
               [0, 0, 1]])
print(Rz)

[[cos(thetaz) -sin(thetaz) 0]
 [sin(thetaz) cos(thetaz) 0]
 [0 0 1]]


In [19]:
Rzyx = Rx @ Ry @ Rz
print(Rzyx)

[[cos(thetay)*cos(thetaz) -sin(thetaz)*cos(thetay) sin(thetay)]
 [sin(thetax)*sin(thetay)*cos(thetaz) + sin(thetaz)*cos(thetax)
  -sin(thetax)*sin(thetay)*sin(thetaz) + cos(thetax)*cos(thetaz)
  -sin(thetax)*cos(thetay)]
 [sin(thetax)*sin(thetaz) - sin(thetay)*cos(thetax)*cos(thetaz)
  sin(thetax)*cos(thetaz) + sin(thetay)*sin(thetaz)*cos(thetax)
  cos(thetax)*cos(thetay)]]


In [20]:
# Rx*Ry*Rz
t2 = cos(thetay)
t3 = sin(thetaz)
t4 = cos(thetaz)
t5 = sin(thetay)
t6 = cos(thetax)
t7 = sin(thetax)
M = [t2 * t4, t3 * t6 + t4 * t5 * t7, t3 * t7 - t4 * t5 * t6, -t2 * t3, t4 * t6 - t3 * t5 * t7,
        t4 * t7 + t3 * t5 * t6, t5, -t2 * t7, t2 * t6]

Mxyz = np.array(M).reshape(3,3).T


print(Mxyz)

[[cos(thetay)*cos(thetaz) -sin(thetaz)*cos(thetay) sin(thetay)]
 [sin(thetax)*sin(thetay)*cos(thetaz) + sin(thetaz)*cos(thetax)
  -sin(thetax)*sin(thetay)*sin(thetaz) + cos(thetax)*cos(thetaz)
  -sin(thetax)*cos(thetay)]
 [sin(thetax)*sin(thetaz) - sin(thetay)*cos(thetax)*cos(thetaz)
  sin(thetax)*cos(thetaz) + sin(thetay)*sin(thetaz)*cos(thetax)
  cos(thetax)*cos(thetay)]]


In [24]:
#Rxyz = Rx.dot(Ry.dot(Rz))
Rxyz = Rz @ Ry @ Rx
print(Rxyz)

[[cos(thetay)*cos(thetaz)
  sin(thetax)*sin(thetay)*cos(thetaz) - sin(thetaz)*cos(thetax)
  sin(thetax)*sin(thetaz) + sin(thetay)*cos(thetax)*cos(thetaz)]
 [sin(thetaz)*cos(thetay)
  sin(thetax)*sin(thetay)*sin(thetaz) + cos(thetax)*cos(thetaz)
  -sin(thetax)*cos(thetaz) + sin(thetay)*sin(thetaz)*cos(thetax)]
 [-sin(thetay) sin(thetax)*cos(thetay) cos(thetax)*cos(thetay)]]


In [25]:
t2 = cos(thetaz)
t3 = sin(thetax)
t4 = sin(thetaz)
t5 = cos(thetax)
t6 = sin(thetay)
t7 = cos(thetay)
Mzx = [t2 * t7, t4 * t7, -t6, -t4 * t5 + t2 * t3 * t6, t2 * t5 + t3 * t4 * t6, t3 * t7, t3 * t4 + t2 * t5 * t6,
        -t2 * t3 + t4 * t5 * t6, t5 * t7]

Mzyx = np.array(Mzx).reshape(3,3).T
print(Mzyx)

[[cos(thetay)*cos(thetaz)
  sin(thetax)*sin(thetay)*cos(thetaz) - sin(thetaz)*cos(thetax)
  sin(thetax)*sin(thetaz) + sin(thetay)*cos(thetax)*cos(thetaz)]
 [sin(thetaz)*cos(thetay)
  sin(thetax)*sin(thetay)*sin(thetaz) + cos(thetax)*cos(thetaz)
  -sin(thetax)*cos(thetaz) + sin(thetay)*sin(thetaz)*cos(thetax)]
 [-sin(thetay) sin(thetax)*cos(thetay) cos(thetax)*cos(thetay)]]
